const constants = {
  formLables: {
    name: "Name",
    email: "Email",
    password: "Password",
    company: "Company",
    dob: "Dob",
    department: "Department",
    mobile: "Mobile",
    profilePicture: "ProfilePicture",
    logo: "Logo",
    joiningDate: "JoiningDate",
    companyName: "Company Name",
    companyAddress: "Company Address",
    experience: "Experience",
    role: "Role",
  },
  buttonLabels: {
    submit: "Submit",
    previous: "Previous",
    next: "Next",
    edit: "Edit",
    delete: "Delete",
    deactive: "Deactive",
    login: 'Login'
  },
  menus: {
    dashboard: "Dashboard",
    workspace: "Workspace",
    employee: "Employee",
    yourProfile: "Your Profile",
    signOut: "Sign out",
  },
  validations: {
    required: "Required",
    invalidEmail: "Invalid email address",
    password_6_characters: "Password must be at least 6 characters",
  },
  dashboardCard: {
    title1: "Total views",
    total1: "$3.456K",
    rate1: "0.43%",
    title2: "Total Profit",
    total2: "$45,2K",
    rate2: "4.35%",
    title3: "Total Product",
    total3: "2.450",
    rate3: "2.59%",
    title4: "Total Users",
    total4: "3.456",
    rate4: "0.95%",
  },
};

export default constants;